added new list_function.js to perform some add and rmove task
sonyco-4u/To-do-list-list-structure pull request #2
Opened 2022-10-06 15:17 UTC by sonyco-4u

#Implement add and remove functions

Remove all hardcoded items from the tasks array.
Create a new JavaScript file for the new functionality.
Implement a function for adding a new task (add a new element to the array).
Implement a function for deleting a task (remove an element from the array).
Implement a function for editing task descriptions.
By default, new tasks should have the property completed set to false and the property index set to the value of the new array length (i.e. if you're adding a 5th task to the list, the index of that task should equal 5).
Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique(i.e. if you're deleting the first task index 1 from the list, the index of the following task(2) should be set to 1).
All changes to the To-Do List should be saved in local storage.

2022-10-06 18:02 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @sonyco-4u :wave:

## Highlights :1st_place_medal:

:heavy_check_mark: Following Github Flow
:heavy_check_mark: Following some requirements
:heavy_check_mark: Meaningful commit messages
:heavy_check_mark: Descriptive PR Title

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-06 18:02 UTC, HAMMAS-SALEEM commented on src/list_functions.js
> +};
- [ ] It would be nice if you export all your functions in this way for example your first function is 

```
exports.add = (inputtext, taskarr) => {
  const len = taskarr.length;
  taskarr.push({
    description: inputtext,
    completed: false,
    index: len + 1,
  });
};
```

You should export is in this way :arrow_down: :heavy_check_mark:
```

export const add = (inputtext, taskarr) => {
  const len = taskarr.length;
  taskarr.push({
    description: inputtext,
    completed: false,
    index: len + 1,
  });
};
```

To follow the ES6 and this is showing some errors in the terminal on myside :thinking: Kindly import all your functions in that way i showed above :+1:

2022-10-06 18:02 UTC, HAMMAS-SALEEM commented on webpack.config.js
> +/*eslint-disable*/
- [ ] Kindly rename your file name from **webpack.config.js** :arrow_right: **webpack.config.cjs** because it is showing an error on my terrminal when i changed it the it worked :blush:

2022-10-06 18:02 UTC, HAMMAS-SALEEM commented on src/list_functions.js
> +
- [ ] I have tried a lot but i am not able to understand how you are implementing your edit functionality because i am not able to edit an existing todo anyway. Can you fix that :blush:

2022-10-07 02:34 UTC, sonyco-4u commented on src/list_functions.js
> +};
I think here leaving it to the default without the export is more better to aviod Eslint error.

2022-10-07 02:34 UTC, sonyco-4u commented on src/list_functions.js
> +
Done its working perfectly

2022-10-07 02:50 UTC, Reem-lab reviewed
# Hi @sonyco-4u,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯
<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>


## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the functionality✅
📌 Good commit messages ✅
📌 Professional README ✅

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-07 02:50 UTC, Reem-lab commented on src/list_functions.js
> +
- [ OPTIONAL ] I think I faced the same error as the previous code reviewer but when I write it like this it worked perfectly I will show an image for the code after update    💯🔥🚀💪🏻😄

![image](https://user-images.githubusercontent.com/58553711/194457533-ce0dd560-9f43-4b35-8e55-91eae7dbee73.png)

2022-10-07 02:50 UTC, Reem-lab approved these changes

2022-10-07 03:03 UTC, sonyco-4u commented on src/list_functions.js
> +
Thank you

2022-10-07 03:04 UTC, merged